apiVersion: v1
kind: Pod
metadata:
  labels:
    app: {{ projectname }}-mysql-pod
  name: {{ projectname }}-mysql-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: mysql01
    image: {{ mysql.image.name }}
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ mysql.resources.requests.memory }}
      limits:
        memory: {{ mysql.resources.limits.memory }}
    ports:
    - containerPort: {{ mysql.port.container }}
      hostPort: {{ mysql.port.host }}
      hostIP: {{ mysql.port.ip }}
      protocol: tcp
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: {{ mysql.rootpassword }}
      - name: MYSQL_DATABASE
        value: {{ mysql.dbname }}
      - name: MYSQL_USER
        value: {{ mysql.user.username }}
      - name: MYSQL_PASSWORD
        value: {{ mysql.user.password }}
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: {{ projectname }}-mysql-data
